start_year: 1980
end_year: 2023
genres: 
  - pop
  - hip-hop
  - rock
  - classical
  - edm
  - jazz
markets: 
  - US
  - JP
  - FR
  - GB
  - DE
  - BR
num_to_search: 100
concat_data_key: "concat.csv"
table_name: "song"
features:
  - danceability
  - energy
  - key
  - loudness
  - mode
  - speechiness
  - acousticness
  - instrumentalness
  - liveness
  - valence
  - tempo
  - duration_ms
  - time_signature
  - sentiment
  - len_song_name
